version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

  app1:
    image: nginx:alpine
    volumes:
      - ./app1:/usr/share/nginx/html:ro

  app2:
    image: nginx:alpine
    volumes:
      - ./app2:/usr/share/nginx/html:ro
